# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Leatherback Monitoring
email: contact@leatherback-monitoring.github.io
description: > # this means to ignore newlines until "baseurl:"
  We are two high school students working to develop an improved method of monitoring sea turtle nest temperatures for biologists in Costa Rica.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://leatherback-monitoring.github.io" # the base hostname & protocol for your site
github_username:  leatherback-monitoring

# Build settings
markdown: kramdown
